### ISSUE TITLE
Enable binder on our repository

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#143]
Binder 2.0 came out today. We should enable it on this repo so people can run the notebooks.

**Comment by ixjlyons** [comment]
I tried this out and there are a couple issues currently:

- It doesn't seem to install dependencies. I think `user-environment.yml` may just need to be renamed to `environment.yml` and it will find that.
- The index file isn't currently very useful for this use case because it links to HTML files. Perhaps we could use relative links to the notebook files (so browsing it on GitHub even works) and then replace them with links to the built notebooks in the build/deploy step on Travis. That seems a bit cleaner anyway.
