### ISSUE TITLE
It may be better to use `add_config_plot_func`

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#67]
At least one student was confused by this. She did:

```python
sys.config_plot_func = my_func
sys.config_plot_func(1, 2, 3, 4)
```

If we did it like we did with "add_measurement" it would be consistent and they wouldn't be able to access this attribute.

**Comment by ixjlyons** [comment]
I think the reason we settled on this was that there's only one config function to add (so it's more of a set, but we don't like `set_attr()` in Python). It's inconsistent with `add_measurement`, but that's because you can add multiple measurements. I actually wouldn't mind a `set_config_plot_func` method. Using add for an attribute there can only be one of is a bit unintuitive.

**Comment by moorepants** [comment]
Yes, that is what we settled on. I just noticed that a student got confused in the above manner. Which may indicate it wasn't a great decision. The setter is less pythonic but may be easier to understand. This has bearing on how the students will set the EoM function too.

**Comment by moorepants** [comment]
Not doing this.
